---
language: ruby
cache: bundler
branches:
  only:
    - master

rvm:
  - 2.1.0

services:
  - postgresql
  - elasticsearch

before_script:
  - psql -c 'create database ministry_test;' -U postgres

script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - bundle exec rspec spec/

